import Head from "next/head";
import { Button, TextField } from "@mui/material";
import Link from "next/link";

const Home = () => {
  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <TextField id="outlined-basic" label="login" variant="outlined" />
          <TextField id="outlined-basic" label="password" variant="outlined" />
          <Link href="/calendar">
            <Button variant="contained">Connexion</Button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
